### ISSUE TITLE
Can't resolve classnames

### ISSUE THREAD

**Issue by kevbarns** [vacarsu/uikit-react#31]
Hello,

I have the following issue right after importing the lib and trying the basic layout you provide in the README = 

./node_modules/uikit-react/lib/uikit-react.js
Module not found: Can't resolve 'classnames' is '/node_modules/uikit-react/lib'

Kevin

**Comment by vacarsu** [comment]
Hi, do you have the classnames dependency installed?

**Comment by vacarsu** [comment]
Try running ```npm install uikit-react``` I've made some updates to the package.json to include peerDependencies. Let me know if this fixes the issue.

**Comment by ayan4m1** [comment]
I just started using this library an hour ago and I ran into this problem. `peerDependencies` haven't been installed during `npm install` since [npm 3](https://github.com/npm/npm/releases/tag/v3.0.0):

> peerDependencies no longer cause anything to be implicitly installed

You could use something like [this](https://www.npmjs.com/package/install-peers), make classnames a dependency outright, or just rely on some users hitting a brick wall and going into the package.json to look for peerDeps.

**Comment by vacarsu** [comment]
Moved classnames from peer to regular dependency. Let me know if there is still issues.

**Comment by kevbarns** [comment]
Hey ! thanks for your feedbacks guys. 

So should I like run npm install again ? 

sorry about that, still getting to know developers life =)

Kevin

**Comment by vacarsu** [comment]
Yeah, simply run ```npm install uikit-react``` again.

**Comment by vacarsu** [comment]
Closing this issue.
